# Generated by Django 6.0.4 on 2026-04-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_alter_manufacturer_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("username",)},
        ),
    ]
